#!/bin/bash
echo -e "\033[32mInitializing test\033[0m"
ls "bytecodes/" |
    while read file
    do
	echo "Testing " $file
	./monty "bytecodes/${file}" 2> err
	echo "Output code " $?
	echo "Error Output " $(cat err)
    done
